server:
  port: 9999

mpesa:
  checkout:
    BusinessShortCode: 174379
    TransactionType: "CustomerPayBillOnline"
    ConsumerKey: "UZe8nJF7XCcnnJzdVgaNNI1v0ceAjeaj"
    PassKey: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    ConsumerSecret: "NmgORhNyknZ1JMaC"
    STKPushUrl: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
    AuthUrl: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
